#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Start/stop aesdsocket server daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
DAEMON_NAME="aesdsocket"

PIDFILE=/var/run/${DAEMON_NAME}.pid

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon --start \
            --background \
            --make-pidfile \
            --pidfile $PIDFILE \
            --exec $DAEMON -- $DAEMON_OPTS
        echo "$DAEMON_NAME started."
        ;;

    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon --stop \
            --pidfile $PIDFILE \
            --retry TERM/5/KILL/5
        rm -f $PIDFILE
        echo "$DAEMON_NAME stopped."
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            if ps -p $PID > /dev/null 2>&1; then
                echo "$DAEMON_NAME is running (PID $PID)"
                exit 0
            fi
        fi
        echo "$DAEMON_NAME is NOT running"
        exit 1
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
